set number			"enable line numbers
set mouse=a			"enables mouse usage
syntax on			"syntax highlighting
set autoindent		"automatically indents when entering code block
set tabstop=4		"tab is the size of 4 spaces
set shiftwidth=4	"when shifting tab = 4 spaces
set smarttab		"uses tabstop as the size of tab (impements tabstop)
set hlsearch		"highlight searched words
set incsearch		"see the words being searched (incremental)
set smartcase		"lowercase = insensitive , uppercase = sensitive
set autowrite		"autosaves when switching between files
set titlestring=%t  "set the vim window title to the file name Eg: test.py
set title			"display that title
set ruler			"displays a ruler in bottom right corner that show cursor position
set confirm			"Display a confirmation dialog when closing an unsaved file.
set laststatus=2	"file status , if written or not (displays a bar at the bottom)
set cursorline	"Enable this if you feel like it
set history=1000	"extend commands history (default =20)
set nowrap 			"lines extend off the edge instead of dropping down in a new line.
set wildmenu		"a menu that shows possible commands when pressing tab
set encoding=UTF-8  "sets encoding to UTF-8
set scrolloff=8   "minimum number of lines to keep above/below cursor
set sidescrolloff=8 "minimum number of columns to keep from edges of the cursor
set visualbell		"use visual bell instead of sound bell
set t_vb=			"disable visual bell
filetype on			"Detect filetype
filetype indent on	"Load indentation settings for this filetype
filetype plugin on	"Load plugging set for this filetype
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx "
set termguicolors  	"add the colors that come with the terminal
colorscheme molokai

"Keyboard Mapping : (:help mapping)

inoremap jj <ESC>		"map jj to switch to normal mode in insert mode
vnoremap ii <ESC>		"map ii to switch to normal mode in visual mode	
snoremap jj <ESC> 		"map jj to switch to normal mode in replace mode 

noremap <c-s> :w<cr>	"Save file by  pressing Ctrl+s
noremap <F8> :w<CR>		"Save the file by pressing <F8>
noremap ; :


nnoremap <s-j> <c-w>j	"Navigate the split view easier
nnoremap <s-k> <c-w>k
nnoremap <s-h> <c-w>h
nnoremap <s-l> <c-w>l


noremap <c-up> <c-w>+	"Resize the split view
noremap <c-down> <c-w>-
noremap <c-left> <c-w>>
noremap <c-right> <c-w><

vnoremap <c-j> :m .-2<CR>==v
vnoremap <c-k> :m .-2<CR>==v	"Move text up/down
vnoremap p _dP

xnoremap J :move '>+1<CR>gv-gv	"Move text blocks up/ down
xnoremap K :move '<-2<CR>gv-gv
xnoremap <c-j> :move '>+1<CR>gv-gv
xnoremap <c-k> :move '<-2<CR>gv-gv

nnoremap <c-j> <ESC>:m .+1<CR>	"Move line up/down
nnoremap <c-k> <Esc>:m .-2<Cr>

vnoremap > >gv
vnoremap < <gv



noremap <c-r> :w<CR>:!java %<CR> 	"switch '!java' with the language you want

"running code using <F9>
autocmd FileType java map <buffer> <F9> :w<CR>:exec '!time java' shellescape(@%, 1)<CR>
autocmd FileType java imap <buffer> <F9> <esc>:w<CR>:exec '!time java' shellescape(@%, 1)<CR>

autocmd FileType python map <buffer> <F9> :w<CR>:exec '!time python3' shellescape(@%, 1)<CR>
autocmd FileType python imap <buffer> <F9> <esc>:w<CR>:exec '!time python3' shellescape(@%, 1)<CR>

"Move 3 times faster by pressing shift
noremap <s-j> 3j
noremap <s-k> 3k

"Copy/Paste to clipboard (requires gvim)
vnoremap <C-c> "+y
noremap <C-v> "+P

